apiVersion: v1
kind: Secret
metadata:
  name: harbor-login-secret
  namespace: default
# 类型必须�?kubernetes.io/dockerconfigjson
type: kubernetes.io/dockerconfigjson
data:
  # 这里�?.dockerconfigjson 需要您手动 base64 编码，或者直接使�?kubectl create secret 命令生成
  # 如果想用�?yaml 创建，请用以下命令生�?base64 并替换下方占位符�?  # echo -n '{"auths":{"192.168.9.41:30002":{"username":"admin","password":"Harbor12345","auth":"YWRtaW46SGFyYm9yMTIzNDU="}}}' | base64 -w 0
  .dockerconfigjson: <BASE64_ENCODED_AUTH_JSON>
